# Generated by Django 4.2.7 on 2023-12-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_task_taskmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='category',
        ),
    ]
