# Generated by Django 4.2.7 on 2023-12-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_taskmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskAssignDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
