# Generated by Django 4.2.7 on 2023-12-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskmodel_id'),
        ('category', '0002_rename_name_categorymodel_categoryname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='task',
            field=models.ManyToManyField(related_name='categories', to='task.taskmodel'),
        ),
    ]
