# Generated by Django 4.2.7 on 2023-12-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_categorymodel_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='task',
        ),
    ]
