# Generated by Django 4.2.7 on 2023-12-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_taskmodel_category'),
        ('category', '0004_remove_categorymodel_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='task',
            field=models.ManyToManyField(to='task.taskmodel'),
        ),
    ]
